version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  samba:
    build:
      context: .
      dockerfile: ./samba/Dockerfile
    restart: always
    privileged: true
    ports:
      - 389:389
      - 389:389/udp
    environment:
      REALM: development.example.com
      WORKGROUP: DEVELOPMENT
    secrets:
      - samba-admin-password

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    ports:
      - 4200:4200
    volumes:
      - node_modules:/workspace/node_modules
    environment:
      PORT: 4200
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    stdin_open: true

volumes:
  node_modules:

secrets:
  samba-admin-password:
    file: ./samba/secrets.txt
